name: Terraform Cost and Tag Check

inputs:
  infracost_token:
    description: 'Infracost API Token'
    required: true
    type: string
  required_tags:
    description: 'Comma-separated list of required tags'
    required: true
    type: string

runs:
  using: "composite"
  # env:
  #   INFRACOST_API_KEY: ${{ inputs.infracost_token }}

  steps:
  - name: echo
    run: echo ${{ inputs.infracost_token }}
    shell: bash

  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Install Infracost
    run: |
      curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
      infracost --version
    shell: bash

  - name: Generate Infracost breakdown
    run: infracost breakdown --path=tfplan.json --format=json --out-file=infracost-report.json
    shell: bash
    env:
      INFRACOST_API_KEY: ${{ inputs.infracost_token }}

  - name: Output Infracost breakdown
    run: infracost output --path=infracost-report.json --format=table
    shell: bash
    env:
      INFRACOST_API_KEY: ${{ inputs.infracost_token }}

  - name: Check for required tags
    run: |
      missing_tags=$(jq -r '.resource_changes[] | select(.type == "aws_instance") | select(.change.after.tags == null or .change.after.tags | has("${{ inputs.required_tags }}") | not) | .address' tfplan.json)
      if [ -n "$missing_tags" ]; then
        echo "Error: The following resources are missing required tags: $missing_tags"
        exit 1
      fi
    env:
      INFRACOST_API_KEY: ${{ inputs.infracost_token }}
    shell: bash
