name: Terraform Cost and Tag Check

inputs:
  infracost_token:
    description: 'Infracost API Token'
    required: true
    type: string
  required_tags:
    description: 'Comma-separated list of required tags'
    required: true
    type: string

runs:
  using: "composite"

  steps:
  - name: echo
    run: echo ${{ inputs.infracost_token }}
    shell: bash

  - name: list
    run: ls -al
    shell: bash

  - name: echo
    run: echo ${GITHUB_ACTION_PATH}
    shell: bash

  - name: Install Infracost
    run: |
      curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
      infracost --version
    shell: bash

  - name: Generate Infracost breakdown
    run: infracost breakdown --path=tfplan.json --format=json --out-file=infracost-report.json
    shell: bash
    env:
      INFRACOST_API_KEY: ${{ inputs.infracost_token }}

  - name: Output Infracost breakdown
    run: infracost output --path=infracost-report.json --format=table
    shell: bash
    env:
      INFRACOST_API_KEY: ${{ inputs.infracost_token }}
