# name: Terraform Check

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v2
#       with:
#         terraform_version: '1.0.0'

#     - name: Initialize Terraform
#       run: terraform init

#     - name: Validate Terraform
#       run: terraform validate

#     - name: Plan Terraform
#       run: terraform plan -out=tfplan.binary

#     - name: Convert Terraform plan to JSON
#       run: terraform show -json tfplan.binary > tfplan.json

#     - name: Call reusable workflow for cost and tag check
#       uses: ./.github/actions/reusable-terraform-check
#       with:
#         infracost_token: ${{ secrets.INFRACOST_API_KEY }}
#         required_tags: 'Owner,Environment'

#     - name: Apply Terraform (optional)
#       if: success() && github.event_name == 'push'
#       run: terraform apply -auto-approve tfplan.binary