name: Terraform Check

# on:
#     pull_request:
#         branches:
#             - main

on:
    workflow_call:

jobs:
    terraform:
        runs-on: ubuntu-latest
        
        env:
            TF_ROOT: .
            REGO_POLICY_DIR: ./policy
            TF_VERSION: 1.7.4
            CONFTEST_VERSION: 0.55.0
            WORKING_DIR: ./
            INFRACOST_API_KEY:  ${{ secrets.INFRACOST_API_KEY }}
        
        permissions:
            contents: read
            # Required to post comments
            pull-requests: write

        steps: 
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
                terraform_version: '1.7.4'
        
          - name: Install Conftest
            run: |
                wget -O - 'https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz' | tar zxvf -
                ./conftest --version

          - name: Initialize Terraform
            run: terraform init

          - name: Validate Terraform
            run: terraform validate

          # Generates an execution plan for Terraform & Saves as json output for conftest validation
          - name: Terraform Plan & Save JSON plan output
            working-directory: ${{ env.WORKING_DIR }}
            run: |
                terraform plan -out=tfplan && \
                terraform show -json tfplan > tfplan.json
        
          - name: Setup Infracost
            uses: infracost/actions/setup@v2
            with:
                api-key: ${{ secrets.INFRACOST_API_KEY }}

        # Checkout the base branch of the pull request (e.g. main/master).
          - name: Checkout base branch
            uses: actions/checkout@v3
            with:
                ref: '${{ github.event.pull_request.base.ref }}'

          - name: list Main
            run: ls -al
            shell: bash

        # Generate Infracost JSON file as the baseline.
          - name: Generate Infracost cost estimate baseline
            shell: bash
            run: |
                infracost breakdown --path=${TF_ROOT} \
                                    --format=json \
                                    --out-file=/tmp/infracost-base.json

        # Checkout the current PR branch so we can create a diff.
          - name: Checkout PR branch
            uses: actions/checkout@v3

          - name: list PR
            run: ls -al
            shell: bash

        # Generate an Infracost diff and save it to a JSON file.
          - name: Generate Infracost diff
            shell: bash
            run: |
                infracost diff --path=${TF_ROOT} \
                                --format=json \
                                --compare-to=/tmp/infracost-base.json \
                                --out-file=/tmp/infracost.json

        # Posts a comment to the PR using the 'update' behavior.
        # This creates a single comment and updates it. The "quietest" option.
        # The other valid behaviors are:
        #   delete-and-new - Delete previous comments and create a new one.
        #   hide-and-new - Minimize previous comments and create a new one.
        #   new - Create a new cost estimate comment on every push.
        # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
          - name: Checkout tools repo
            uses: actions/checkout@v4
            with:
                repository: Ajay-Chidambaram/terraform-infracost-action

          - name: Post Infracost comment
            shell: bash
            run: |
                infracost comment github --path=/tmp/infracost.json \
                                            --repo=$GITHUB_REPOSITORY \
                                            --github-token=${{github.token}} \
                                            --pull-request=${{github.event.pull_request.number}} \
                                            --behavior=update \
                                            --policy-path ${REGO_POLICY_DIR}/infracost.rego
