name: Terraform Check

on:
    pull_request:
        branches:
            - main

jobs:
    terraform:
        runs-on: ubuntu-latest
        
        env:
            TF_ROOT: .
            REGO_POLICY_DIR: ./policy
            TF_VERSION: 1.7.4
            CONFTEST_VERSION: 0.55.0
            WORKING_DIR: ./
        
        permissions:
            contents: read
            # Required to post comments
            pull-requests: write

        steps: 
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
                terraform_version: '1.7.4'
        
          - name: Install Conftest
            run: |
                wget -O - 'https://github.com/open-policy-agent/conftest/releases/download/v${{ env.CONFTEST_VERSION }}/conftest_${{ env.CONFTEST_VERSION }}_Linux_x86_64.tar.gz' | tar zxvf -
                ./conftest --version

          - name: Initialize Terraform
            run: terraform init

          - name: Validate Terraform
            run: terraform validate

          # Generates an execution plan for Terraform & Saves as json output for conftest validation
          - name: Terraform Plan & Save JSON plan output
            working-directory: ${{ env.WORKING_DIR }}
            run: |
                terraform plan -out=tfplan && \
                terraform show -json tfplan > tfplan.json

          - name: echo 
            run : | 
                ls -al
                echo  ${{ env.WORKING_DIR }}

        #   - name: Run Conftest Test
        #     id: conftest
        #     run: ./conftest test ${{ env.WORKING_DIR }}tfplan.json -o github
        
          - name: Call reusable workflow for cost and tag check
            uses: ./.github/actions/reusable-terraform-check
            with:
                infracost_token: ${{ secrets.INFRACOST_API_KEY }}
                required_tags: 'Owner,Environment'